adminDashboard/urls.py
from . import views
from django.urls import path


app_name = 'admin_dash'
urlpatterns = [
    path('', views.admin_dash, name='admin_dash'),
    path('register/', views.register_user, name='register'),
    path('create_student/', views.create_student, name='create_student'),
    path('create_employee/', views.create_employee, name='create_employee'),
    path('create_school_year/', views.school_year, name='school_year'),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('accounts.urls')),
    path('admin_dash/', include('adminDashboard.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
]

"""Add the following line to serve media files during development"""
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminDashboard/models.py
from django.db import models
from classes.models import Class_student
# Create your models here.

class School_Year(models.Model):
    year_name = models.CharField(max_length=9, unique=True, help_text="Format: YYYY-YYYY (e.g., 2023-2024)")

    def __str__(self):
        return self.year_name

    class Meta:
        verbose_name_plural = "School Years"
class School_Year_Class(models.Model):
    schoolYear = models.ForeignKey(School_Year, on_delete=models.SET_NULL, null=True, blank=False)
    student_in_class = models.ForeignKey(Class_student, on_delete=models.SET_NULL, null=True, blank=False)
    free = models.IntegerField()

adminDashboard/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from accounts.models import CustomUser  # Import your CustomUser model if it exists
from students.models import Student, Family

from .models import School_Year_Class, School_Year

class CustomUserRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'user_role', ]

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
class SchoolYearClassForm(forms.ModelForm):
    class Meta:
        model = School_Year_Class
        fields = '__all__'
class SchoolYearForm(forms.ModelForm):
    class Meta:
        model = School_Year
        fields = '__all__'
class FamilyForm(forms.ModelForm):
    class Meta:
        model = Family
        fields = '__all__'


   

adminDashboard/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from accounts.decorators import admin_required
from teachers.models import Teacher
from classes.models import Class_room, Subject
from .forms import CustomUserRegistrationForm, StudentForm, FamilyForm, SchoolYearForm,SchoolYearClassForm
from .models import School_Year
from employees.forms import EmployeesForm
from employees.models import Employees
from accounts.models import CustomUser
from students.models import Student
from teachers.models import Teacher, Teacher_subject, ReferenceBook, Grade
from .managers import CustomUserManager


@admin_required
def school_year(request):

    if request.method == 'POST':
        form = SchoolYearForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_dash:admin_dash')
    else:
        form = SchoolYearForm()
    return render(request, 'adminDashboard/SchoolYear.html', {'yearForm': form})

@admin_required
def admin_dash(request):
    students = Student.objects.all()
    teachers = Teacher.objects.all()
    classes = Class_room.objects.all()
    subjects = Subject.objects.all()
    if School_Year.objects.all() == 0:
        return redirect('admin_dash:school_year')
    else:
        context = {
            'students': students,
            'teachers': teachers,
            'classes': classes,
            'subjects': subjects,
        }

        return render(request, 'adminDashboard/base.html', context)
@admin_required
def register_user(request):
    if request.method == 'POST':
        form = CustomUserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin_dash:admin_dash')
    else:
        form = CustomUserRegistrationForm()

    context = {'form': form}
    return render(request, 'adminDashboard/register.html', context)

@admin_required
def create_student(request):
    if request.method == 'POST':
        student_form = StudentForm(request.POST)
        family_form = FamilyForm(request.POST)

        if student_form.is_valid() and family_form.is_valid():
            family = family_form.save()
            student = student_form.save(commit=False)

            student.family_id = family
            student.save()
            user_role_value = 'student'
            initial_data = {
                'username': student.first_name,
                'email': student.email,
                'user_role': user_role_value,
            }
            user_model = get_user_model()
            user = user_model.objects.create_user(**initial_data)
            user.set_password(student.first_name)
            user.save()
            return redirect('admin_dash:admin_dash')

    else:
        student_form = StudentForm()
        family_form = FamilyForm()

    return render(request, 'adminDashboard/create_student.html', {'student_form': student_form, 'family_form': family_form})

def create_employee(request):
    if request.method == 'POST':
        employees_form = EmployeesForm(request.POST)

        if employees_form.is_valid():
            employee = employees_form.save()
            employee.save()
            return redirect('admin_dash:admin_dash')

    else:
        employees_form = EmployeesForm()

    return render(request, 'adminDashboard/create_employee.html', {'employees_form': employees_form})


@admin_required
def update_student(request, pk):
    student = Student.objects.get(id=pk);
    form = StudentForm(instance=student) # previous

    if request.method == 'POST':
        form = StudentForm(request.POST or None , instance=student )
        if form.is_valid():
            form.save();
        return redirect('/admin-dashboard/')
    context={'form': form}
    return render (request,'adminDashboard/updateStudent.html',context );

@admin_required
def delete_student(request, pk):
    student = student.object.get(id=pk);
    
    if request.method == 'POST':
        student.delete()
        return redirect('/')
    context = {'student': student}
    return render(request, 'adminDashboard/delete_student.html', context)


            

adminDashboard/templates/adminDashboard/SchoolYear.html
<!DOCTYPE html>
<html>
<head>
    <title>School Year</title>
</head>
<body>
    <h2>School Year</h2>
    <form method="post">
        {% csrf_token %}
        {{ yearForm.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>

adminDashboard/templates/adminDashboard/create_employee.html
<!DOCTYPE html>
<html>
<head>
    <title>Employee Registration</title>
</head>
<body>
    <h2>Employee Registration</h2>
    <form method="post">
        {% csrf_token %}
        {{ employees_form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>

adminDashboard/templates/adminDashboard/create_student.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Student</title>
</head>
<body>
    <h1>Create Student</h1>
    <form method="post">
        {% csrf_token %}
        {{ student_form.as_p }}
        <h2>Family Information</h2>
        {{ family_form.as_p }}
        <button type="submit">Create</button>
    </form>
</body>
</html>

adminDashboard/templates/adminDashboard/family_registration.html
<!DOCTYPE html>
<html>
<head>
    <title>Family Registration</title>
</head>
<body>
    <h1>Family Registration</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>

adminDashboard/templates/adminDashboard/register.html
<!DOCTYPE html>
<html>
<head>
    <title>User Registration</title>
</head>
<body>
    <h2>User Registration</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</body>
</html>

adminDashboard/templates/adminDashboard/student_registration.html
<!DOCTYPE html>
<html>
  <head>
    <title>Student Registration</title>
  </head>
  <body>
    <h1>Student Registration</h1>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Register</button>
    </form>
  </body>
</html>

adminDashboard/templates/adminDashboard/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> student list </h1>
<ul>
    {% for student in students %}
    <li>{{ student.first_name }}</li>
    {% endfor %}
</ul>
<a href="{% url 'admin_dash:register' %}">Register User</a>
<br></br>
<a href="{% url 'admin_dash:create_student' %}">Register Student</a>
<a href="{% url 'admin_dash:create_employee' %}">Register Employee</a>
<a href="{% url 'admin_dash:school_year' %}">Register New School year</a>
</body>
</html>